//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -14
        ///+15
        ///+9
        ///+19
        ///+18
        ///+14
        ///+14
        ///-18
        ///+15
        ///+4
        ///-18
        ///-20
        ///-2
        ///+17
        ///+16
        ///-7
        ///-3
        ///+5
        ///+1
        ///-5
        ///-11
        ///-1
        ///-6
        ///-20
        ///+1
        ///+1
        ///+4
        ///+18
        ///+5
        ///-20
        ///-10
        ///+18
        ///+5
        ///-4
        ///-5
        ///-18
        ///+9
        ///+6
        ///+1
        ///-19
        ///+13
        ///+10
        ///-22
        ///-11
        ///-14
        ///-17
        ///-10
        ///-1
        ///-13
        ///+6
        ///-17
        ///+9
        ///-11
        ///-6
        ///+3
        ///-14
        ///+4
        ///-14
        ///+15
        ///+7
        ///+15
        ///-1
        ///-4
        ///+9
        ///+10
        ///+6
        ///-9
        ///+8
        ///+3
        ///+10
        ///-14
        ///+8
        ///+22
        ///+19
        ///-15
        ///+10
        ///-6
        ///+9
        ///-4
        ///+2
        ///+11
        ///-15
        ///+14
        ///+11
        ///-14
        ///+2
        ///+7
        ///+9
        ///-22
        ///-6
        ///-3
        ///-21
        ///+10
        ///+5
        ///-20
        ///+19
        ///-3
        ///-13
        ///+5
        ///-16
        ///+12
        ///+10
        ///-12
        ///-4
        ///+12
        ///+2
        ///-1
        ///-4
        ///-8
        ///-6
        ///-3
        ///-8
        ///-8
        ///+7        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
