//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day4 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day4.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-06-02 23:58] Guard #179 begins shift
        ///[1518-09-18 00:43] wakes up
        ///[1518-06-06 00:10] falls asleep
        ///[1518-05-12 00:52] wakes up
        ///[1518-07-02 00:39] wakes up
        ///[1518-07-21 23:50] Guard #2917 begins shift
        ///[1518-09-22 00:47] wakes up
        ///[1518-09-09 00:31] wakes up
        ///[1518-07-21 00:15] wakes up
        ///[1518-07-30 00:43] wakes up
        ///[1518-10-08 00:52] wakes up
        ///[1518-07-26 23:57] Guard #1051 begins shift
        ///[1518-07-17 00:00] Guard #2273 begins shift
        ///[1518-08-18 00:24] falls asleep
        ///[1518-09-08 00:02] falls asleep
        ///[1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-11-01 00:00] Guard #10 begins shift
        ///[1518-11-01 00:05] falls asleep
        ///[1518-11-01 00:25] wakes up
        ///[1518-11-01 00:30] falls asleep
        ///[1518-11-01 00:55] wakes up
        ///[1518-11-01 23:58] Guard #99 begins shift
        ///[1518-11-02 00:40] falls asleep
        ///[1518-11-02 00:50] wakes up
        ///[1518-11-03 00:05] Guard #10 begins shift
        ///[1518-11-03 00:24] falls asleep
        ///[1518-11-03 00:29] wakes up
        ///[1518-11-04 00:02] Guard #99 begins shift
        ///[1518-11-04 00:36] falls asleep
        ///[1518-11-04 00:46] wakes up
        ///[1518-11-05 00:03] Guard #99 b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestInput {
            get {
                return ResourceManager.GetString("TestInput", resourceCulture);
            }
        }
    }
}
