//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day10 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day10.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position=&lt; 20247,  40241&gt; velocity=&lt;-2, -4&gt;
        ///position=&lt; 10184, -29948&gt; velocity=&lt;-1,  3&gt;
        ///position=&lt; 50313, -39966&gt; velocity=&lt;-5,  4&gt;
        ///position=&lt;-19870, -19921&gt; velocity=&lt; 2,  2&gt;
        ///position=&lt; 10224, -49995&gt; velocity=&lt;-1,  5&gt;
        ///position=&lt;-19904,  20191&gt; velocity=&lt; 2, -2&gt;
        ///position=&lt; 50300,  -9887&gt; velocity=&lt;-5,  1&gt;
        ///position=&lt;-29924, -29942&gt; velocity=&lt; 3,  3&gt;
        ///position=&lt;-29903, -29939&gt; velocity=&lt; 3,  3&gt;
        ///position=&lt;-29905,  50273&gt; velocity=&lt; 3, -5&gt;
        ///position=&lt; 20222, -29944&gt; velocity=&lt;-2,  3&gt;
        ///position=&lt; 40293, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position=&lt; 9,  1&gt; velocity=&lt; 0,  2&gt;
        ///position=&lt; 7,  0&gt; velocity=&lt;-1,  0&gt;
        ///position=&lt; 3, -2&gt; velocity=&lt;-1,  1&gt;
        ///position=&lt; 6, 10&gt; velocity=&lt;-2, -1&gt;
        ///position=&lt; 2, -4&gt; velocity=&lt; 2,  2&gt;
        ///position=&lt;-6, 10&gt; velocity=&lt; 2, -2&gt;
        ///position=&lt; 1,  8&gt; velocity=&lt; 1, -1&gt;
        ///position=&lt; 1,  7&gt; velocity=&lt; 1,  0&gt;
        ///position=&lt;-3, 11&gt; velocity=&lt; 1, -2&gt;
        ///position=&lt; 7,  6&gt; velocity=&lt;-1, -1&gt;
        ///position=&lt;-2,  3&gt; velocity=&lt; 1,  0&gt;
        ///position=&lt;-4,  3&gt; velocity=&lt; 2,  0&gt;
        ///position=&lt;10, -3&gt; velocity=&lt;-1,  1&gt;
        ///position=&lt; 5, 11&gt; velocity=&lt; 1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestInput {
            get {
                return ResourceManager.GetString("TestInput", resourceCulture);
            }
        }
    }
}
