//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day8 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day8.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 11 6 2 4 3 3 6 1 8 0 11 3 3 6 7 4 7 6 3 4 7 1 3 3 3 2 1 1 2 3 1 8 0 7 7 1 7 9 2 5 9 2 1 3 1 2 3 3 2 1 9 0 11 2 2 4 5 5 3 7 6 1 6 5 3 1 3 3 1 1 1 1 1 2 1 5 4 4 3 3 4 1 8 0 8 1 6 7 5 3 7 5 9 2 2 3 2 2 3 1 1 1 8 0 6 4 1 5 4 5 6 1 1 3 1 1 1 1 1 1 8 0 6 1 5 8 8 5 6 1 1 2 2 1 2 1 1 2 2 2 3 3 4 1 8 0 7 3 3 1 4 3 6 7 3 2 2 3 2 3 3 1 1 5 0 10 3 8 1 2 4 1 8 9 7 3 1 3 1 1 1 1 5 0 8 8 9 9 3 5 1 6 1 1 3 1 2 2 2 1 1 3 3 4 1 6 0 6 9 1 4 2 7 7 3 2 1 2 2 3 1 8 0 8 8 1 1 3 3 6 1 3 2 1 1 1 1 2 1 2 1 7 0 7 3 9 7 1 5 1 5 1 2  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 3 0 3 10 11 12 1 1 0 1 99 2 1 1 2.
        /// </summary>
        internal static string TestInput {
            get {
                return ResourceManager.GetString("TestInput", resourceCulture);
            }
        }
    }
}
